[package]
name = "flights"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
