/// calculator operations
interface calculator {

    /// add two numbers
    add: func(a: f32, b: f32) -> f32;

    /// subtract the second number from the first
    subtract: func(a: f32, b: f32) -> f32;

    /// multiply two numbers
    multiply: func(a: f32, b: f32) -> f32;

    /// divide the first number by the second
    divide: func(a: f32, b: f32) -> f32;
}

/// the calculator world
world calculator-world {
    export calculator;
}
