interface flights {
    record flight {
        id: string,
        airline: string,
        number: string,
        origin: string,
        destination: string,
        departure: string,
        arrival: string,
    }

    record flight-search {
        arrival: option<string>,
        departure: string,
        destination: string,
        flex: option<s32>,
        origin: string,
    }

    get-flights: func() -> list<flight>;

    search-flights: func(data: flight-search) -> list<flight>;

    get-flight-by-id: func(id: string) -> option<flight>;
}

world flights-world {
    include wasi:config/imports@0.2.0-draft;
    import rest-client;
    export flights;
}
