interface hotels {
    record hotel {
        id: string,
        name: string,
        city: string,
        stars: s32,
        description: string,
    }

    record hotel-search {
        checkin: string,
        checkout: string,
        city: string,
        flex: option<s32>,
        minstars: option<s32>,
    }

    get-hotels: func() -> list<hotel>;

    search-hotels: func(data: hotel-search) -> list<hotel>;

    get-hotel-by-id: func(id: string) -> option<hotel>;
}

world hotels-world {
    include wasi:config/imports@0.2.0-draft;
    import rest-client;
    export hotels;
}
